### ISSUE TITLE
List of style examples missing in FTD 0.3

### ISSUE THREAD

**Issue by MeenuKumari28** [ftd-lang/ftd#485]

**Comment by vikas-growisto** [comment]
Thanks for resolving the issues, below attributes are working in 0.3
-` border-color, border-top-color, border-bottom-color, border-left-color, border-right-color,`
- `min-height, max-height, min-width`
- `border-radius,border-top-left-radius, border-top-right-radius, border-bottom-left-radius and `border-bottom-right-radius`

But in the max-width, there is one issue that we are still facing i.e. when max-width is smaller than the content height should increase which is not happening 
`-- ftd.text: FifthTry
max-width.px: 20`

**Comment by vikas-growisto** [comment]
@Arpita-Jaiswal align-self isn't working in 0.3
or am I making some mistake in writing it

`-- ftd.row:
min-width.px: 300
padding.px: 20

-- ftd.text: FifthTry
max-width.px: 20
background.solid: $yellow
align-self: center

-- end: ftd.row

-- ftd.color yellow:
light: yellow
dark: yellow`

FPM-Error: path: list, PackageError { message: "failed to parse ParseError { message: \"hello/list/: not found (\\\"hello/list/#center\\\"), f: search_thing\", doc_id: \"hello/list/\", line_number: 8 }" }

**Comment by vikas-growisto** [comment]
text-align is also not working in 0.3

`-- ftd.text: FifthTry`
`min-width.px: 200`
`text-align: center`

FPM-Error: path: list, PackageError { message: "failed to parse ParseError { message: \"hello/list/: not found (\\\"hello/list/#center\\\"), f: search_thing\", doc_id: \"hello/list/\", line_number: 3 }" }

**Comment by vikas-growisto** [comment]
Margin properties are working now. margin-right, margin-left, margin-top and margin-bottom

`-- ftd.text: Hello`
`margin.px: 60`

**Comment by vikas-growisto** [comment]
@Arpita-Jaiswal @MeenuKumari28 these attributes are also not working in 0.3

1. background-gradient
2. background-image
3. background-parallax
4. shadow-offset-x and shadow-offset-y
5. shadow-blur
6. shadow-size
7. text-transform & text-align
8. align-self
9. sticky
10. overflow-x & overflow-y
11. style
12. z-index

**Comment by gsalunke** [comment]
Closing issue as this list is maintained in https://github.com/ftd-lang/ftd/issues/492
