### ISSUE TITLE
Desktop and Mobile device detection condition not working in FTD 0.3

### ISSUE THREAD

**Issue by MeenuKumari28** [ftd-lang/ftd#488]
We have tried using FTD 0.2 device detection condition into FTD 0.3 as given below:

```ftd
-- boolean is-mobile: false

-- is-mobile: true
if: $ftd.device == mobile
```
But it throws below error:

```ftd
'ParseError { message: "Expected condition in expression mode, found: $ftd.device == mobile", doc_id: "foo", line_number: 4 }'
```

@Arpita-Jaiswal how do we use mobile device detection condition into FTD 0.3?

**Comment by gsalunke** [comment]
Closing as this is added into issue: https://github.com/ftd-lang/ftd/issues/492
